apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistantVolume.name }}
spec:
  accessModes:
    - {{ .Values.persistantVolume.accessModes }}
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
  storageClassName: manual

