apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-service
  name: db-service
spec:
  ports:
  - name: {{ .Values.service_db.name }}
    port: {{ .Values.service_db.port }}
    protocol: TCP
    targetPort: {{ .Values.service_db.targetPort }}
  selector:
    app: database
  type: ClusterIP
status:
  loadBalancer: {}
