apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: {{ .Values.service_frontend.name }}
    port: {{ .Values.service_frontend.port }}
    protocol: TCP
    targetPort: {{ .Values.service_frontend.targetPort }}
    nodePort: {{ .Values.service_frontend.nodePort }}
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
